stages:
  - development

image: cirrusci/android-sdk:30

variables:
  JAVA_VERSION: "17"

default:
  before_script:
    - apt-get update && apt-get install -y ruby-full curl unzip
    - ruby -v
    - gem install bundler fastlane
    - bundler -v
    - fastlane -v
    - chmod +x ./gradlew
    - apt-get install -y openjdk-${JAVA_VERSION}-jdk
    - java -version

deploy to development:
  stage: development
  script:
    - echo "Starting the Android build"
    - bundle install
    - bundle exec fastlane distribute
