stages:
  - setup
  - build

variables:
  RUBY_VERSION: "3.2.2"
  JAVA_VERSION: "17"
  ANDROID_HOME: "/usr/local/android-sdk"
  ANDROID_SDK_CMDLINE_TOOLS: "/usr/local/android-sdk/cmdline-tools/latest"
  ANDROID_SDK_URL: "https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip"

before_script:
  - apt-get update && apt-get install -y curl unzip
  - curl -sL https://deb.nodesource.com/setup_18.x | bash -
  - apt-get install -y nodejs
  - npm install -g npm@latest
  - apt-get install -y ruby-full
  - gem install bundler
  - gem install fastlane
  - bundle install
  - chmod +x ./gradlew
  - apt-get install -y openjdk-17-jdk
  - java -version

  # إعداد SDK الأندرويد
  - mkdir -p ${ANDROID_HOME}/cmdline-tools
  - curl -sL ${ANDROID_SDK_URL} -o android-cmdline-tools.zip
  - unzip android-cmdline-tools.zip -d ${ANDROID_HOME}/cmdline-tools
  - rm android-cmdline-tools.zip
  - mv ${ANDROID_HOME}/cmdline-tools/cmdline-tools ${ANDROID_SDK_CMDLINE_TOOLS}

  # حذف مجلد platform-tools القديم إذا كان موجودًا
  - rm -rf ${ANDROID_HOME}/platform-tools

  # تثبيت الأدوات مرة أخرى
  - yes | ${ANDROID_SDK_CMDLINE_TOOLS}/bin/sdkmanager --sdk_root=${ANDROID_HOME} "platform-tools" "build-tools;30.0.3" "platforms;android-30"
  - yes | ${ANDROID_SDK_CMDLINE_TOOLS}/bin/sdkmanager --licenses

setup:
  stage: setup
  script:
    - ruby -v
    - bundler -v
    - fastlane -v
    - bundle install
    - echo "Android SDK installed at ${ANDROID_HOME}"

build:
  stage: build
  script:
    - echo "Starting the Android build"
    - bundle exec fastlane distribute
