stages:
  - setup
  - build

variables:
  RUBY_VERSION: "3.2.2"
  JAVA_VERSION: "17"

before_script:
  - apt-get update && apt-get install -y curl
  - curl -sL https://deb.nodesource.com/setup_18.x | bash -
  - apt-get install -y nodejs
  - npm install -g npm@latest
  - apt-get install -y ruby-full
  - gem install bundler
  - gem install fastlane
  - bundle install
  - mkdir -p "$ANDROID_HOME"
  - curl -sL https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -o commandlinetools.zip
  - unzip commandlinetools.zip -d "$ANDROID_HOME"
  - yes | "$ANDROID_HOME/tools/bin/sdkmanager" --sdk_root="$ANDROID_HOME" "platform-tools" "build-tools;30.0.3" "android-29"  # Install necessary SDK packages
  - echo "sdk.dir=$ANDROID_HOME" > local.properties  # Dynamically create local.properties
  - chmod +x ./gradlew

setup:
  stage: setup
  script:
    - ruby -v
    - bundler -v
    - fastlane -v
    - bundle install

build:
  stage: build
  script:
    - apt-get install -y openjdk-17-jdk
    - java -version
    - fastlane -v
    - bundle exec fastlane distribute
