image: cirrusci/android-sdk:33

stages:
  - deploy

variables:
  SECURE_FILES_DIR: "${CI_PROJECT_DIR}/.secure-files"  # المسار الصحيح للملفات الآمنة

deploy_to_firebase:
  stage: deploy
  before_script:
    - mkdir -p "${SECURE_FILES_DIR}"
  script:
    # --------------------- الخطوة 1: نسخ الملف الآمن ---------------------
    - echo "CI_SECURE_FILES path: ${CI_SECURE_FILES}"
    - ls -la "${CI_SECURE_FILES}"  # التحقق من وجود الملف
    - cp "${CI_SECURE_FILES}/google-service-secrets.json" ./
    
    # --------------------- الخطوة 2: التحقق من الملف ---------------------
    - ls -la  # التأكد من ظهور الملف في المسار الجذر
    - file google-service-secrets.json  # التحقق من نوع الملف
    - jq empty google-service-secrets.json || exit 1  # التحقق من صحة JSON
    
    # --------------------- الخطوة 3: إصلاح الصلاحيات ---------------------
    - chmod 644 google-service-secrets.json  # منح صلاحيات القراءة
    
    # --------------------- الخطوة 4: تشغيل Fastlane ---------------------
    - bundle install
    - bundle exec fastlane distribute

  only:
    - main

  after_script:
    - rm -f google-service-secrets.json  # حذف الملف بعد الانتهاء