stages:
  - build
  - deploy

variables:
  JAVA_VERSION: "17"
  SECRETS_FILE: "google-service-secrets.json"

image: cirrusci/android-sdk:33

before_script:
  - apt-get update -qq && apt-get install -y -qq ruby-full unzip jq
  - gem install bundler
  - bundle install

deploy_to_development:
  stage: deploy
  script:
    - echo "$GOOGLE_SERVICE_SECRETS" | base64 -d > "${SECRETS_FILE}"

    - ls -la
    - file "${SECRETS_FILE}"
    - jq empty "${SECRETS_FILE}" || (echo "Invalid JSON file!" && exit 1)

    - chmod 644 "${SECRETS_FILE}"

    - bundle exec fastlane distribute_development
  only:
    - tags
    - development
    - /^v-dev-.*/

deploy_to_production:
  stage: deploy
  script:
    - echo "$GOOGLE_SERVICE_SECRETS" | base64 -d > "${SECRETS_FILE}"
    - chmod 644 "${SECRETS_FILE}"
    - bundle exec fastlane distribute_production
  only:
    - main

after_script:
  - rm -f "${SECRETS_FILE}"