stages:
  - setup
  - build

image: cirrusci/android-sdk:30

variables:
  JAVA_VERSION: "17"
  ANDROID_HOME: "/sdk"
  ANDROID_SDK_CMDLINE_TOOLS: "${ANDROID_HOME}/cmdline-tools/latest"

default:
  before_script:
    - apt-get update && apt-get install -y ruby-full curl unzip
    - ruby -v
    - gem install bundler fastlane
    - bundler -v
    - fastlane -v
    - chmod +x ./gradlew
    - apt-get install -y openjdk-${JAVA_VERSION}-jdk
    - java -version

setup:
  stage: setup
  script:
    - echo "Using pre-installed Android SDK"
    - echo "Android SDK located at ${ANDROID_HOME}"
    - sdkmanager --list # التحقق من الأدوات المثبتة

build:
  stage: build
  script:
    - echo "Starting the Android build"
    - bundle install
    - bundle exec fastlane distribute
