stages:
  - build
  - deploy

variables:
  JAVA_VERSION: "17"
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

# Use modern Android SDK image
image: cirrusci/android-sdk:33

before_script:
  - apt-get update -qq && apt-get install -y -qq ruby-full unzip
  - gem install bundler
  - bundle install

deploy_to_development:
  stage: deploy
  script:
    # CORRECTED: Secure files path (remove .secure-files from path)
    - cp "${CI_SECURE_FILES}/google-service-secrets.json" ./

    # Set proper permissions
    - chmod 644 google-service-secrets.json

    # Verify file existence
    - ls -la

    # Execute deployment
    - bundle exec fastlane distribute_development
  only:
    - tags
    - development
    - /^v-dev-.*/

deploy_to_production:
  stage: deploy
  script:
    - cp "${CI_SECURE_FILES}/google-service-secrets.json" ./
    - chmod 644 google-service-secrets.json
    - bundle exec fastlane distribute_production
  only:
    - main

after_script:
  # Cleanup secrets file
  - rm -f google-service-secrets.json