stages:
  - setup
  - build

variables:
  RUBY_VERSION: "3.2.2"
  JAVA_VERSION: "17"

before_script:
  - apt-get update && apt-get install -y curl
  - curl -sL https://deb.nodesource.com/setup_18.x | bash -
  - apt-get install -y nodejs
  - npm install -g npm@latest # تحديث `npm`
  - chmod +x ./gradlew # إذا كنت تستخدم Gradle

setup:
  stage: setup
  script:
    - apt-get update && apt-get install -y ruby-full
    - gem install bundler
    - bundle install

build:
  stage: build
  script:
    - apt-get install -y openjdk-17-jdk
    - java -version
    - bundle exec fastlane distribute
