stages:
  - development
  - production

image: cirrusci/android-sdk:30

variables:
  JAVA_VERSION: "17"

default:
  before_script:
    - apt-get update && apt-get install -y ruby-full curl unzip
    - ruby -v
    - gem install bundler fastlane
    - bundler -v
    - fastlane -v
    - chmod +x ./gradlew
    - apt-get install -y openjdk-${JAVA_VERSION}-jdk
    - java -version

deploy to development:
  stage: development
  script:
    - echo "Starting the Android build"
    - bundle install
    - bundle exec fastlane update_version_from_branch_tag
    - bundle exec fastlane distribute

  only:
     refs:
       - /^feature.*$/
       - /^feat.*$/
       - development
       - tags
     variables:
       - $CI_COMMIT_TAG

deploy to production:
  stage: development
  script:
    - echo "Starting the Android build"
    - bundle install
    - bundle exec fastlane update_version_for_new_feature
    - bundle exec fastlane distribute

  only:
    - ff