stages:
  - development
  - production

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

image: cirrusci/android-sdk:33

before_script:
  - apt-get update -qq
  - apt-get install -y -qq ruby-full unzip openjdk-17-jdk
  - update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
  - java -version
  - gem install bundler
  - bundle install
  - chmod +x ./gradlew
  - ls -la ./gradlew

deploy-to-development:
  stage: development
  script:
    - echo "ENCODED_GOOGLE_SERVICES= ${ENCODED_GOOGLE_SERVICES:0:10}..."
    - echo "$ENCODED_GOOGLE_SERVICES" | base64 -d > google-service-secrets.json
    - chmod 644 google-service-secrets.json
    - bundle exec fastlane distribute
  rules:
    - if: '$CI_COMMIT_REF_NAME == "development"'
    - if: '$CI_COMMIT_TAG =~ /^v-dev-/'

deploy-to-production:
  stage: production
  script:
    - echo "$ENCODED_GOOGLE_SERVICES" | base64 --decode > google-service-secrets.json
    - chmod 644 google-service-secrets.json
    - bundle exec fastlane distribute
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main" && $CI_COMMIT_TAG =~ /^v-prod-/'

after_script:
  - rm -f google-services.json