stages:
  - setup
  - build

variables:
  RUBY_VERSION: "3.2.2"
  JAVA_VERSION: "17"

before_script:
  - apt-get update && apt-get install -y curl
  - curl -sL https://deb.nodesource.com/setup_18.x | bash -
  - apt-get install -y nodejs
  - npm install -g npm@latest
  - apt-get install -y ruby-full
  - gem install bundler
  - gem install fastlane
  - fastlane add_plugin firebase_app_distribution
  - bundle install
  - chmod +x ./gradlew

setup:
  stage: setup
  script:
    - ruby -v
    - bundler -v
    - fastlane -v
    - bundle install

build:
  stage: build
  script:
    - apt-get install -y openjdk-17-jdk
    - java -version
    - fastlane -v
    - bundle exec fastlane distribute
