stages:
  - setup
  - build
  - deploy

variables:
  RUBY_VERSION: "3.2.2"
  JAVA_VERSION: "17"

before_script:
  - apt-get update && apt-get install -y curl
  - curl -sL https://deb.nodesource.com/setup_14.x | bash -
  - apt-get install -y nodejs
  - npm install -g firebase-tools
  - chmod +x ./gradlew

setup:
  stage: setup
  script:
    - apt-get update && apt-get install -y ruby-full
    - gem install bundler
    - bundle install

build:
  stage: build
  script:
    - echo "Setting up Java $JAVA_VERSION"
    - apt-get install -y openjdk-17-jdk
    - bundle exec fastlane distribute
