name: Development

on:
  push:
    branches:
      - development
      - feat*
      - feature*

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      ORIGIN: ${{ secrets.ORIGIN }}

    steps:
      - name: Create Google Service Secrets file safely
        run: |
          mkdir -p fastlane
          printf "%s" "$GOOGLE_SERVICE_SECRETS" > fastlane/google-service-secrets.json
        env:
          GOOGLE_SERVICE_SECRETS: ${{ secrets.GOOGLE_SERVICE_SECRETS }}

      - name: Decode Google Service Secrets
        run: echo "$GOOGLE_SERVICE_SECRETS" > fastlane/google-service-secrets.json
        env:
          GOOGLE_SERVICE_SECRETS: ${{ secrets.GOOGLE_SERVICE_SECRETS }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if Tag starts with "v-"
        if: ${{ (github.event.ref_type == 'tag' && startsWith(github.ref_name, 'v-'))||startsWith(github.ref_name, 'testCi') }}
        run: echo "Deploying version = ${{ github.ref_name }}"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Install Firebase tool (if needed)
        run: npm install -g firebase-tools

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Git identity
        run: |
          git config --global user.email "ahmed.sheref.3.96@gmail.com"
          git config --global user.name "ahmed sheref"

      - name: Set execute permission for gradlew (if using Gradle)
        run: chmod +x ./gradlew

      - name: set branch name
        run: echo "GIT_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV

#      - name: Run Fastlane Lane
#        run: bundle exec fastlane tag_commit_if_needed

      - name: deploy to development
        run: bundle exec fastlane distribute