name: Production

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Install Firebase tool (if needed)
        run: npm install -g firebase-tools

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set execute permission for gradlew (if using Gradle)
        run: chmod +x ./gradlew
      - name: set branch name
        run: export GIT_BRANCH=$github.ref_name

      - name: Run Fastlane Lane
        run: bundle exec fastlane tag_commit_if_needed

      - name: deploy to production
        run: bundle exec fastlane distribute